### ISSUE TITLE
Routes - `events/reserve/:id`

### ISSUE THREAD

**Issue by JasonQiu21** [JasonQiu21/goodminton#6]
Create route `POST events/reserve/:id` to sign a player up for an event and `DELETE events/reserve/:id` to delete a reservation

request body:
```yaml
playerId: str # ObjectId str that represents player
time: Optional[datetime] # time slot they are signing up for - null if tournament sign-up
court: Optional[int] # court number they are signing up for
```
